### ISSUE TITLE
Cannot export Excel from rounds

### ISSUE THREAD

**Issue by thrichter** [geziefer/tgiu2#25]
When trying to get an excel export I get the following error:

```
java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.CellStyle.setAlignment(S)V
	at org.primefaces.component.export.ExcelExporter.applyOptions(ExcelExporter.java:290)
	at org.primefaces.component.export.ExcelExporter.export(ExcelExporter.java:75)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:134)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)

```

This was working before. Not sure what has changed. Wildfly is fixed on V13 since we deployed this.

Possible solution:
https://stackoverflow.com/questions/49147668/primefaces-error-on-exporting-data-xls-java-lang-nosuchmethoderror-poi-cel

**Comment by thrichter** [comment]
Cannot reproduce in latest update anymore.
